{
 "title": "T4 temperature check midday",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "test_date",
    "label": "Date",
    "query": "select to_char(timestamp,  'YYYY/MM/DD')\nfrom temperature_dt_scas_test \nwhere status LIKE '%done%'\norder by 1 desc"
   },
   {
    "name": "test_id",
    "query": "select id from temperature_dt_scas_test where to_char(timestamp, 'YYYY/MM/DD') = ${test_date:singlequote} "
   },
   {
    "name": "test_status",
    "query": "select \nconcat(to_char(timestamp, 'YYYY/DD/MM HH:MM'), ' -> ', status)\nfrom temperature_dt_scas_test where id = $test_id"
   },
   {
    "name": "step",
    "query": "SELECT  DATE_PART('day', now()::timestamp - ${test_date:singlequote}::timestamp) as step"
   },
   {
    "name": "t_from_temp",
    "query": "select EXTRACT(EPOCH from  timestamp )*1000  - 4200000 from temperature_dt_scas_test where to_char(timestamp, 'YYYY/MM/DD') = ${test_date:singlequote} "
   },
   { "name": "t_to_temp", "query": "select $t_from_temp + 600000;" },
   {
    "name": "t_from",
    "query": "select EXTRACT(EPOCH from DATE_TRUNC('day', timestamp ))*1000  from temperature_dt_scas_test where to_char(timestamp, 'YYYY/MM/DD') = ${test_date:singlequote} order by timestamp desc;"
   },
   { "name": "t_to", "query": "select $t_from + 86400000;" }
  ]
 },
 "panels": [
  {
   "title": "Coldest LOOPs",
   "type": "table",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  1 as \"join\",\n  sb.subfield_name,\n  ss.name as sector_name,\n  ls.name,\n  sca4_temp\nFROM\n  temperature_dt_scas_daily td \n  inner join loop_sensors ls on td.loop_id = ls.loop_id\n  inner join sca_sensors sca on ls.loop_id = sca.loop_id\n  inner join subfield_sensors sb on ls.subfield_id = sb.subfield_id\n  inner join sector_sensors ss on sb.sector_id = ss.sector_id\nWHERE\n  test_id = $test_id and sca4_temp > 300 and sca_position = 4\norder by sca4_temp asc limit 10"
    },
    {
     "rawSql": "SELECT\n  1 as \"join\",\n  avg(sca4_temp) as average,\n--  percentile_disc(0.90) within group (order by sca4_temp)   as \"P90\",\n--  percentile_disc(0.50) within group (order by sca4_temp)+5 as \"P50+5\",\n--  percentile_disc(0.50) within group (order by sca4_temp)   as \"P50\",\n  percentile_disc(0.50) within group (order by sca4_temp)-5 as \"P50-5\",\n  percentile_disc(0.10) within group (order by sca4_temp)   as \"P10\"\nFROM\n(SELECT\n  sca4_temp\nFROM\n  temperature_dt_scas_daily td inner join loop_sensors ls on td.loop_id = ls.loop_id\nWHERE\n  test_id = $test_id and sca4_temp > 300 \n) s1"
    }
   ]
  },
  {
   "title": "Recurrently cold LOOPs",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "select\n\tsubfield_name,\n\tsector_name,\n\tname\nfrom (\n\tselect\n\t  sb.subfield_name,\n\t  ss.name as sector_name,\n\t  ls.name,\n\t  sca4_temp\n\tFROM\n\t  temperature_dt_scas_daily td \n\t  inner join loop_sensors ls on td.loop_id = ls.loop_id\n\t  inner join sca_sensors sca on ls.loop_id = sca.loop_id\n\t  inner join subfield_sensors sb on ls.subfield_id = sb.subfield_id\n\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\tWHERE\n\t  sca4_temp > 300 and sca_position = 4 and \n\t  test_id in (select distinct(test_id)\n\t\t\tfrom temperature_dt_scas_test tdst \n\t\t\tinner join temperature_dt_scas_daily td on tdst.id = td.test_id\n\t\t\twhere test_id <= $test_id\n\t\t\torder by test_id desc limit 3)\n\torder by sca4_temp asc limit 30) s1\ngroup by subfield_name, sector_name, name HAVING count(name) >= 3 "
    }
   ]
  },
  {
   "title": "NNW",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 2, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  percentile_disc(0.50) within group (order by sca4_temp)+5 as \"P50+5\",\n  percentile_disc(0.90) within group (order by sca4_temp)   as \"P90\",\n  percentile_disc(0.50) within group (order by sca4_temp)   as \"P50\",\n  percentile_disc(0.10) within group (order by sca4_temp)   as \"P10\",\n  percentile_disc(0.50) within group (order by sca4_temp)-5 as \"P50-5\"\nFROM\n(SELECT\n  sca4_temp\nFROM\n  temperature_dt_scas_daily td inner join loop_sensors ls on td.loop_id = ls.loop_id\n  inner join subfield_sensors sb on ls.subfield_id = sb.subfield_id\n  inner join sector_sensors ss on sb.sector_id = ss.sector_id\nWHERE\n  test_id = $test_id and ss.name = 'NNW'\n ) s1"
    }
   ]
  },
  {
   "title": "Sector NNW",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 11, "w": 10, "x": 2, "y": 12 },
   "targets": [
    {
     "rawSql": "with data as(\n\tSELECT\n\t    row_number() OVER () AS id,\n\t\tname.sca_name,\n\t  \tname.sca4_temp,\n\t  \tpercen.\"P90\",\n\t  \tpercen.\"P50+5\",\n\t  \tpercen.\"P50\",\n\t\tpercen.\"P50-5\",\n\t\tpercen.\"P10\"\n\tfrom (SELECT\n\t\t  percentile_disc(0.90) within group (order by sca4_temp)   as \"P90\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)+5 as \"P50+5\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)   as \"P50\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)-5 as \"P50-5\",\n\t\t  percentile_disc(0.10) within group (order by sca4_temp)   as \"P10\"\n\t\tFROM\n\t\t(SELECT\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on td.loop_id = sca.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'NNW' and sca_position = 4\n\t\t) s1) percen,\n\t\t(select\n\t\t  sca.subfield_id,\n\t\t  sca_name,\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on sca.loop_id = td.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'NNW' and sca_position = 4\n\t\torder by sca_name asc\n\t\t) name\n)\n(select \n  1 as \"join\",\n\tdata.id,\n\tdata.sca_name,\n\tsca4_temp as outlier\nfrom data\nwhere data.sca4_temp <= data.\"P50-5\")"
    },
    {
     "rawSql": "with data as(\n\tSELECT\n\t    row_number() OVER () AS id,\n\t\tname.sca_name,\n\t  \tname.sca4_temp,\n\t  \tpercen.\"P90\",\n\t  \tpercen.\"P50+5\",\n\t  \tpercen.\"P50\",\n\t\tpercen.\"P50-5\",\n\t\tpercen.\"P10\"\n\tfrom (SELECT\n\t\t  percentile_disc(0.90) within group (order by sca4_temp)   as \"P90\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)+5 as \"P50+5\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)   as \"P50\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)-5 as \"P50-5\",\n\t\t  percentile_disc(0.10) within group (order by sca4_temp)   as \"P10\"\n\t\tFROM\n\t\t(SELECT\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on td.loop_id = sca.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'NNW' and sca_position = 4\n\t\t) s1) percen,\n\t\t(select\n\t\t  sca.subfield_id,\n\t\t  sca_name,\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on sca.loop_id = td.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'NNW' and sca_position = 4\n\t\torder by sca_name asc\n\t\t) name\n)\n(select \n  1 as \"join\",\n\tdata.id,\n\tdata.sca_name,\n\tsca4_temp as regular,\n\t\"P90\",\n\t\"P50+5\",\n\t\"P50\",\n\t\"P50-5\",\n\t\"P10\"\nfrom data\nwhere data.sca4_temp > data.\"P50-5\")"
    }
   ]
  },
  {
   "title": "Sector NNE",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 11, "w": 10, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "with data as(\n\tSELECT\n\t    row_number() OVER () AS id,\n\t\tname.sca_name,\n\t  \tname.sca4_temp,\n\t  \tpercen.\"P90\",\n\t  \tpercen.\"P50+5\",\n\t  \tpercen.\"P50\",\n\t\tpercen.\"P50-5\",\n\t\tpercen.\"P10\"\n\tfrom (SELECT\n\t\t  percentile_disc(0.90) within group (order by sca4_temp)   as \"P90\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)+5 as \"P50+5\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)   as \"P50\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)-5 as \"P50-5\",\n\t\t  percentile_disc(0.10) within group (order by sca4_temp)   as \"P10\"\n\t\tFROM\n\t\t(SELECT\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on td.loop_id = sca.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'NNE' and sca_position = 4\n\t\t) s1) percen,\n\t\t(select\n\t\t  sca.subfield_id,\n\t\t  sca_name,\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on sca.loop_id = td.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'NNE' and sca_position = 4\n\t\torder by sca_name asc\n\t\t) name\n)\n(select \n  1 as \"join\",\n\tdata.id,\n\tdata.sca_name,\n\tsca4_temp as outlier\nfrom data\nwhere data.sca4_temp <= data.\"P50-5\")"
    },
    {
     "rawSql": "with data as(\n\tSELECT\n\t    row_number() OVER () AS id,\n\t\tname.sca_name,\n\t  \tname.sca4_temp,\n\t  \tpercen.\"P90\",\n\t  \tpercen.\"P50+5\",\n\t  \tpercen.\"P50\",\n\t\tpercen.\"P50-5\",\n\t\tpercen.\"P10\"\n\tfrom (SELECT\n\t\t  percentile_disc(0.90) within group (order by sca4_temp)   as \"P90\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)+5 as \"P50+5\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)   as \"P50\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)-5 as \"P50-5\",\n\t\t  percentile_disc(0.10) within group (order by sca4_temp)   as \"P10\"\n\t\tFROM\n\t\t(SELECT\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on td.loop_id = sca.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'NNE' and sca_position = 4\n\t\t) s1) percen,\n\t\t(select\n\t\t  sca.subfield_id,\n\t\t  sca_name,\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on sca.loop_id = td.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'NNE' and sca_position = 4\n\t\torder by sca_name asc\n\t\t) name\n)\n(select \n  1 as \"join\",\n\tdata.id,\n\tdata.sca_name,\n\tsca4_temp as regular,\n\t\"P90\",\n\t\"P50+5\",\n\t\"P50\",\n\t\"P50-5\",\n\t\"P10\"\nfrom data\nwhere data.sca4_temp > data.\"P50-5\")"
    }
   ]
  },
  {
   "title": "NNE",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 2, "x": 22, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  percentile_disc(0.50) within group (order by sca4_temp)+5 as \"P50+5\",\n  percentile_disc(0.90) within group (order by sca4_temp)   as \"P90\",\n  percentile_disc(0.50) within group (order by sca4_temp)   as \"P50\",\n  percentile_disc(0.10) within group (order by sca4_temp)   as \"P10\",\n  percentile_disc(0.50) within group (order by sca4_temp)-5 as \"P50-5\"\nFROM\n(SELECT\n  sca4_temp\nFROM\n  temperature_dt_scas_daily td inner join loop_sensors ls on td.loop_id = ls.loop_id\n  inner join subfield_sensors sb on ls.subfield_id = sb.subfield_id\n  inner join sector_sensors ss on sb.sector_id = ss.sector_id\nWHERE\n  test_id = $test_id and ss.name = 'NNE'\n ) s1"
    }
   ]
  },
  {
   "title": "NW",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 2, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  percentile_disc(0.50) within group (order by sca4_temp)+5 as \"P50+5\",\n  percentile_disc(0.90) within group (order by sca4_temp)   as \"P90\",\n  percentile_disc(0.50) within group (order by sca4_temp)   as \"P50\",\n  percentile_disc(0.10) within group (order by sca4_temp)   as \"P10\",\n  percentile_disc(0.50) within group (order by sca4_temp)-5 as \"P50-5\"\nFROM\n(SELECT\n  sca4_temp\nFROM\n  temperature_dt_scas_daily td inner join loop_sensors ls on td.loop_id = ls.loop_id\n  inner join subfield_sensors sb on ls.subfield_id = sb.subfield_id\n  inner join sector_sensors ss on sb.sector_id = ss.sector_id\nWHERE\n  test_id = $test_id and ss.name = 'NW'\n ) s1"
    }
   ]
  },
  {
   "title": "Sector NW",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 11, "w": 10, "x": 2, "y": 23 },
   "targets": [
    {
     "rawSql": "with data as(\n\tSELECT\n\t    row_number() OVER () AS id,\n\t\tname.sca_name,\n\t  \tname.sca4_temp,\n\t  \tpercen.\"P90\",\n\t  \tpercen.\"P50+5\",\n\t  \tpercen.\"P50\",\n\t\tpercen.\"P50-5\",\n\t\tpercen.\"P10\"\n\tfrom (SELECT\n\t\t  percentile_disc(0.90) within group (order by sca4_temp)   as \"P90\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)+5 as \"P50+5\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)   as \"P50\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)-5 as \"P50-5\",\n\t\t  percentile_disc(0.10) within group (order by sca4_temp)   as \"P10\"\n\t\tFROM\n\t\t(SELECT\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on td.loop_id = sca.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'NW' and sca_position = 4\n\t\t) s1) percen,\n\t\t(select\n\t\t  sca.subfield_id,\n\t\t  sca_name,\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on sca.loop_id = td.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'NW' and sca_position = 4\n\t\t\torder by sca_name asc\n\t\t) name\n)\n(select \n  1 as \"join\",\n\tdata.id,\n\tdata.sca_name,\n\tsca4_temp as outlier\nfrom data\nwhere data.sca4_temp <= data.\"P50-5\")"
    },
    {
     "rawSql": "with data as(\n\tSELECT\n\t    row_number() OVER () AS id,\n\t\tname.sca_name,\n\t  \tname.sca4_temp,\n\t  \tpercen.\"P90\",\n\t  \tpercen.\"P50+5\",\n\t  \tpercen.\"P50\",\n\t\tpercen.\"P50-5\",\n\t\tpercen.\"P10\"\n\tfrom (SELECT\n\t\t  percentile_disc(0.90) within group (order by sca4_temp)   as \"P90\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)+5 as \"P50+5\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)   as \"P50\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)-5 as \"P50-5\",\n\t\t  percentile_disc(0.10) within group (order by sca4_temp)   as \"P10\"\n\t\tFROM\n\t\t(SELECT\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on td.loop_id = sca.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'NW' and sca_position = 4\n\t\t) s1) percen,\n\t\t(select\n\t\t  sca.subfield_id,\n\t\t  sca_name,\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on sca.loop_id = td.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'NW' and sca_position = 4\n\t\torder by sca_name asc\n\t\t) name\n)\n(select \n  1 as \"join\",\n\tdata.id,\n\tdata.sca_name,\n\tsca4_temp as regular,\n\t\"P90\",\n\t\"P50+5\",\n\t\"P50\",\n\t\"P50-5\",\n\t\"P10\"\nfrom data\nwhere data.sca4_temp > data.\"P50-5\")"
    }
   ]
  },
  {
   "title": "Sector NE",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 11, "w": 10, "x": 12, "y": 23 },
   "targets": [
    {
     "rawSql": "with data as(\n\tSELECT\n\t    row_number() OVER () AS id,\n\t\tname.sca_name,\n\t  \tname.sca4_temp,\n\t  \tpercen.\"P90\",\n\t  \tpercen.\"P50+5\",\n\t  \tpercen.\"P50\",\n\t\tpercen.\"P50-5\",\n\t\tpercen.\"P10\"\n\tfrom (SELECT\n\t\t  percentile_disc(0.90) within group (order by sca4_temp)   as \"P90\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)+5 as \"P50+5\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)   as \"P50\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)-5 as \"P50-5\",\n\t\t  percentile_disc(0.10) within group (order by sca4_temp)   as \"P10\"\n\t\tFROM\n\t\t(SELECT\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on td.loop_id = sca.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'NE' and sca_position = 4\n\t\t) s1) percen,\n\t\t(select\n\t\t  sca.subfield_id,\n\t\t  sca_name,\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on sca.loop_id = td.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'NE' and sca_position = 4\n\t\torder by sca_name asc\n\t\t) name\n)\n(select \n  1 as \"join\",\n\tdata.id,\n\tdata.sca_name,\n\tsca4_temp as outlier\nfrom data\nwhere data.sca4_temp <= data.\"P50-5\")"
    },
    {
     "rawSql": "with data as(\n\tSELECT\n\t    row_number() OVER () AS id,\n\t\tname.sca_name,\n\t  \tname.sca4_temp,\n\t  \tpercen.\"P90\",\n\t  \tpercen.\"P50+5\",\n\t  \tpercen.\"P50\",\n\t\tpercen.\"P50-5\",\n\t\tpercen.\"P10\"\n\tfrom (SELECT\n\t\t  percentile_disc(0.90) within group (order by sca4_temp)   as \"P90\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)+5 as \"P50+5\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)   as \"P50\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)-5 as \"P50-5\",\n\t\t  percentile_disc(0.10) within group (order by sca4_temp)   as \"P10\"\n\t\tFROM\n\t\t(SELECT\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on td.loop_id = sca.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'NE' and sca_position = 4\n\t\t) s1) percen,\n\t\t(select\n\t\t  sca.subfield_id,\n\t\t  sca_name,\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on sca.loop_id = td.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'NE' and sca_position = 4\n\t\torder by sca_name asc\n\t\t) name\n)\n(select \n  1 as \"join\",\n\tdata.id,\n\tdata.sca_name,\n\tsca4_temp as regular,\n\t\"P90\",\n\t\"P50+5\",\n\t\"P50\",\n\t\"P50-5\",\n\t\"P10\"\nfrom data\nwhere data.sca4_temp > data.\"P50-5\")"
    }
   ]
  },
  {
   "title": "NE",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 2, "x": 22, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  percentile_disc(0.50) within group (order by sca4_temp)+5 as \"P50+5\",\n  percentile_disc(0.90) within group (order by sca4_temp)   as \"P90\",\n  percentile_disc(0.50) within group (order by sca4_temp)   as \"P50\",\n  percentile_disc(0.10) within group (order by sca4_temp)   as \"P10\",\n  percentile_disc(0.50) within group (order by sca4_temp)-5 as \"P50-5\"\nFROM\n(SELECT\n  sca4_temp\nFROM\n  temperature_dt_scas_daily td inner join loop_sensors ls on td.loop_id = ls.loop_id\n  inner join subfield_sensors sb on ls.subfield_id = sb.subfield_id\n  inner join sector_sensors ss on sb.sector_id = ss.sector_id\nWHERE\n  test_id = $test_id and ss.name = 'NE'\n ) s1"
    }
   ]
  },
  {
   "title": "SW",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 2, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  percentile_disc(0.50) within group (order by sca4_temp)+5 as \"P50+5\",\n  percentile_disc(0.90) within group (order by sca4_temp)   as \"P90\",\n  percentile_disc(0.50) within group (order by sca4_temp)   as \"P50\",\n  percentile_disc(0.10) within group (order by sca4_temp)   as \"P10\",\n  percentile_disc(0.50) within group (order by sca4_temp)-5 as \"P50-5\"\nFROM\n(SELECT\n  sca4_temp\nFROM\n  temperature_dt_scas_daily td inner join loop_sensors ls on td.loop_id = ls.loop_id\n  inner join subfield_sensors sb on ls.subfield_id = sb.subfield_id\n  inner join sector_sensors ss on sb.sector_id = ss.sector_id\nWHERE\n  test_id = $test_id and ss.name = 'SW'\n ) s1"
    }
   ]
  },
  {
   "title": "Sector SW",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 11, "w": 10, "x": 2, "y": 34 },
   "targets": [
    {
     "rawSql": "with data as(\n\tSELECT\n\t    row_number() OVER () AS id,\n\t\tname.sca_name,\n\t  \tname.sca4_temp,\n\t  \tpercen.\"P90\",\n\t  \tpercen.\"P50+5\",\n\t  \tpercen.\"P50\",\n\t\tpercen.\"P50-5\",\n\t\tpercen.\"P10\"\n\tfrom (SELECT\n\t\t  percentile_disc(0.90) within group (order by sca4_temp)   as \"P90\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)+5 as \"P50+5\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)   as \"P50\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)-5 as \"P50-5\",\n\t\t  percentile_disc(0.10) within group (order by sca4_temp)   as \"P10\"\n\t\tFROM\n\t\t(SELECT\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on td.loop_id = sca.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'SW' and sca_position = 4\n\t\t) s1) percen,\n\t\t(select\n\t\t  sca.subfield_id,\n\t\t  sca_name,\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on sca.loop_id = td.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'SW' and sca_position = 4\n\t\torder by sca_name asc\n\t\t) name\n)\n(select \n  1 as \"join\",\n\tdata.id,\n\tdata.sca_name,\n\tsca4_temp as outlier\nfrom data\nwhere data.sca4_temp <= data.\"P50-5\")"
    },
    {
     "rawSql": "with data as(\n\tSELECT\n\t    row_number() OVER () AS id,\n\t\tname.sca_name,\n\t  \tname.sca4_temp,\n\t  \tpercen.\"P90\",\n\t  \tpercen.\"P50+5\",\n\t  \tpercen.\"P50\",\n\t\tpercen.\"P50-5\",\n\t\tpercen.\"P10\"\n\tfrom (SELECT\n\t\t  percentile_disc(0.90) within group (order by sca4_temp)   as \"P90\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)+5 as \"P50+5\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)   as \"P50\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)-5 as \"P50-5\",\n\t\t  percentile_disc(0.10) within group (order by sca4_temp)   as \"P10\"\n\t\tFROM\n\t\t(SELECT\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on td.loop_id = sca.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'SW' and sca_position = 4\n\t\t) s1) percen,\n\t\t(select\n\t\t  sca.subfield_id,\n\t\t  sca_name,\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on sca.loop_id = td.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'SW' and sca_position = 4\n\t\torder by sca_name asc\n\t\t) name\n)\n(select \n  1 as \"join\",\n\tdata.id,\n\tdata.sca_name,\n\tsca4_temp as regular,\n\t\"P90\",\n\t\"P50+5\",\n\t\"P50\",\n\t\"P50-5\",\n\t\"P10\"\nfrom data\nwhere data.sca4_temp > data.\"P50-5\")"
    }
   ]
  },
  {
   "title": "Sector SE",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 11, "w": 10, "x": 12, "y": 34 },
   "targets": [
    {
     "rawSql": "with data as(\n\tSELECT\n\t    row_number() OVER () AS id,\n\t\tname.sca_name,\n\t  \tname.sca4_temp,\n\t  \tpercen.\"P90\",\n\t  \tpercen.\"P50+5\",\n\t  \tpercen.\"P50\",\n\t\tpercen.\"P50-5\",\n\t\tpercen.\"P10\"\n\tfrom (SELECT\n\t\t  percentile_disc(0.90) within group (order by sca4_temp)   as \"P90\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)+5 as \"P50+5\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)   as \"P50\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)-5 as \"P50-5\",\n\t\t  percentile_disc(0.10) within group (order by sca4_temp)   as \"P10\"\n\t\tFROM\n\t\t(SELECT\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on td.loop_id = sca.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'SE' and sca_position = 4\n\t\t) s1) percen,\n\t\t(select\n\t\t  sca.subfield_id,\n\t\t  sca_name,\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on sca.loop_id = td.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'SE' and sca_position = 4\n\t\torder by sca_name asc\n\t\t) name\n)\n(select \n  1 as \"join\",\n\tdata.id,\n\tdata.sca_name,\n\tsca4_temp as outlier\nfrom data\nwhere data.sca4_temp <= data.\"P50-5\")"
    },
    {
     "rawSql": "with data as(\n\tSELECT\n\t    row_number() OVER () AS id,\n\t\tname.sca_name,\n\t  \tname.sca4_temp,\n\t  \tpercen.\"P90\",\n\t  \tpercen.\"P50+5\",\n\t  \tpercen.\"P50\",\n\t\tpercen.\"P50-5\",\n\t\tpercen.\"P10\"\n\tfrom (SELECT\n\t\t  percentile_disc(0.90) within group (order by sca4_temp)   as \"P90\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)+5 as \"P50+5\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)   as \"P50\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)-5 as \"P50-5\",\n\t\t  percentile_disc(0.10) within group (order by sca4_temp)   as \"P10\"\n\t\tFROM\n\t\t(SELECT\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on td.loop_id = sca.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'SE' and sca_position = 4\n\t\t) s1) percen,\n\t\t(select\n\t\t  sca.subfield_id,\n\t\t  sca_name,\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on sca.loop_id = td.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'SE' and sca_position = 4\n\t\t\torder by sca_name asc\n\t\t) name\n)\n(select \n  1 as \"join\",\n\tdata.id,\n\tdata.sca_name,\n\tsca4_temp as regular,\n\t\"P90\",\n\t\"P50+5\",\n\t\"P50\",\n\t\"P50-5\",\n\t\"P10\"\nfrom data\nwhere data.sca4_temp > data.\"P50-5\")"
    }
   ]
  },
  {
   "title": "SE",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 2, "x": 22, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  percentile_disc(0.50) within group (order by sca4_temp)+5 as \"P50+5\",\n  percentile_disc(0.90) within group (order by sca4_temp)   as \"P90\",\n  percentile_disc(0.50) within group (order by sca4_temp)   as \"P50\",\n  percentile_disc(0.10) within group (order by sca4_temp)   as \"P10\",\n  percentile_disc(0.50) within group (order by sca4_temp)-5 as \"P50-5\"\nFROM\n(SELECT\n  sca4_temp\nFROM\n  temperature_dt_scas_daily td inner join loop_sensors ls on td.loop_id = ls.loop_id\n  inner join subfield_sensors sb on ls.subfield_id = sb.subfield_id\n  inner join sector_sensors ss on sb.sector_id = ss.sector_id\nWHERE\n  test_id = $test_id and ss.name = 'SE'\n ) s1"
    }
   ]
  },
  {
   "title": "SSW",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 2, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  percentile_disc(0.50) within group (order by sca4_temp)+5 as \"P50+5\",\n  percentile_disc(0.90) within group (order by sca4_temp)   as \"P90\",\n  percentile_disc(0.50) within group (order by sca4_temp)   as \"P50\",\n  percentile_disc(0.10) within group (order by sca4_temp)   as \"P10\",\n  percentile_disc(0.50) within group (order by sca4_temp)-5 as \"P50-5\"\nFROM\n(SELECT\n  sca4_temp\nFROM\n  temperature_dt_scas_daily td inner join loop_sensors ls on td.loop_id = ls.loop_id\n  inner join subfield_sensors sb on ls.subfield_id = sb.subfield_id\n  inner join sector_sensors ss on sb.sector_id = ss.sector_id\nWHERE\n  test_id = $test_id and ss.name = 'SSW'\n ) s1"
    }
   ]
  },
  {
   "title": "Sector SSW",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 11, "w": 10, "x": 2, "y": 45 },
   "targets": [
    {
     "rawSql": "with data as(\n\tSELECT\n\t    row_number() OVER () AS id,\n\t\tname.sca_name,\n\t  \tname.sca4_temp,\n\t  \tpercen.\"P90\",\n\t  \tpercen.\"P50+5\",\n\t  \tpercen.\"P50\",\n\t\tpercen.\"P50-5\",\n\t\tpercen.\"P10\"\n\tfrom (SELECT\n\t\t  percentile_disc(0.90) within group (order by sca4_temp)   as \"P90\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)+5 as \"P50+5\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)   as \"P50\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)-5 as \"P50-5\",\n\t\t  percentile_disc(0.10) within group (order by sca4_temp)   as \"P10\"\n\t\tFROM\n\t\t(SELECT\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on td.loop_id = sca.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'SSW' and sca_position = 4\n\t\t) s1) percen,\n\t\t(select\n\t\t  sca.subfield_id,\n\t\t  sca_name,\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on sca.loop_id = td.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'SSW' and sca_position = 4\n\t\t\torder by sca_name asc\n\t\t) name\n)\n(select \n  1 as \"join\",\n\tdata.id,\n\tdata.sca_name,\n\tsca4_temp as outlier\nfrom data\nwhere data.sca4_temp <= data.\"P50-5\")"
    },
    {
     "rawSql": "with data as(\n\tSELECT\n\t    row_number() OVER () AS id,\n\t\tname.sca_name,\n\t  \tname.sca4_temp,\n\t  \tpercen.\"P90\",\n\t  \tpercen.\"P50+5\",\n\t  \tpercen.\"P50\",\n\t\tpercen.\"P50-5\",\n\t\tpercen.\"P10\"\n\tfrom (SELECT\n\t\t  percentile_disc(0.90) within group (order by sca4_temp)   as \"P90\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)+5 as \"P50+5\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)   as \"P50\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)-5 as \"P50-5\",\n\t\t  percentile_disc(0.10) within group (order by sca4_temp)   as \"P10\"\n\t\tFROM\n\t\t(SELECT\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on td.loop_id = sca.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'SSW' and sca_position = 4\n\t\t) s1) percen,\n\t\t(select\n\t\t  sca.subfield_id,\n\t\t  sca_name,\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on sca.loop_id = td.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'SSW' and sca_position = 4\n\t\t\torder by sca_name asc\n\t\t) name\n)\n(select \n  1 as \"join\",\n\tdata.id,\n\tdata.sca_name,\n\tsca4_temp as regular,\n\t\"P90\",\n\t\"P50+5\",\n\t\"P50\",\n\t\"P50-5\",\n\t\"P10\"\nfrom data\nwhere data.sca4_temp > data.\"P50-5\")"
    }
   ]
  },
  {
   "title": "Sector SSE",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 11, "w": 10, "x": 12, "y": 45 },
   "targets": [
    {
     "rawSql": "with data as(\n\tSELECT\n\t    row_number() OVER () AS id,\n\t\tname.sca_name,\n\t  \tname.sca4_temp,\n\t  \tpercen.\"P90\",\n\t  \tpercen.\"P50+5\",\n\t  \tpercen.\"P50\",\n\t\tpercen.\"P50-5\",\n\t\tpercen.\"P10\"\n\tfrom (SELECT\n\t\t  percentile_disc(0.90) within group (order by sca4_temp)   as \"P90\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)+5 as \"P50+5\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)   as \"P50\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)-5 as \"P50-5\",\n\t\t  percentile_disc(0.10) within group (order by sca4_temp)   as \"P10\"\n\t\tFROM\n\t\t(SELECT\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on td.loop_id = sca.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'SSE' and sca_position = 4\n\t\t) s1) percen,\n\t\t(select\n\t\t  sca.subfield_id,\n\t\t  sca_name,\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on sca.loop_id = td.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'SSE' and sca_position = 4\n\t\t\torder by sca_name asc\n\t\t) name\n)\n(select \n  1 as \"join\",\n\tdata.id,\n\tdata.sca_name,\n\tsca4_temp as outlier\nfrom data\nwhere data.sca4_temp <= data.\"P50-5\")"
    },
    {
     "rawSql": "with data as(\n\tSELECT\n\t    row_number() OVER () AS id,\n\t\tname.sca_name,\n\t  \tname.sca4_temp,\n\t  \tpercen.\"P90\",\n\t  \tpercen.\"P50+5\",\n\t  \tpercen.\"P50\",\n\t\tpercen.\"P50-5\",\n\t\tpercen.\"P10\"\n\tfrom (SELECT\n\t\t  percentile_disc(0.90) within group (order by sca4_temp)   as \"P90\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)+5 as \"P50+5\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)   as \"P50\",\n\t\t  percentile_disc(0.50) within group (order by sca4_temp)-5 as \"P50-5\",\n\t\t  percentile_disc(0.10) within group (order by sca4_temp)   as \"P10\"\n\t\tFROM\n\t\t(SELECT\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on td.loop_id = sca.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'SSE' and sca_position = 4\n\t\t) s1) percen,\n\t\t(select\n\t\t  sca.subfield_id,\n\t\t  sca_name,\n\t\t  sca4_temp\n\t\tFROM\n\t\t  temperature_dt_scas_daily td \n\t\t  inner join sca_sensors sca on sca.loop_id = td.loop_id\n\t\t  inner join subfield_sensors sb on sca.subfield_id = sb.subfield_id\n\t\t  inner join sector_sensors ss on sb.sector_id = ss.sector_id\n\t\tWHERE\n\t\t  test_id = $test_id and ss.name = 'SSE' and sca_position = 4\n\t\t\torder by sca_name asc\n\t\t) name\n)\n(select \n  1 as \"join\",\n\tdata.id,\n\tdata.sca_name,\n\tsca4_temp as regular,\n\t\"P90\",\n\t\"P50+5\",\n\t\"P50\",\n\t\"P50-5\",\n\t\"P10\"\nfrom data\nwhere data.sca4_temp > data.\"P50-5\")"
    }
   ]
  },
  {
   "title": "SSE",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 2, "x": 22, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  percentile_disc(0.50) within group (order by sca4_temp)+5 as \"P50+5\",\n  percentile_disc(0.90) within group (order by sca4_temp)   as \"P90\",\n  percentile_disc(0.50) within group (order by sca4_temp)   as \"P50\",\n  percentile_disc(0.10) within group (order by sca4_temp)   as \"P10\",\n  percentile_disc(0.50) within group (order by sca4_temp)-5 as \"P50-5\"\nFROM\n(SELECT\n  sca4_temp\nFROM\n  temperature_dt_scas_daily td inner join loop_sensors ls on td.loop_id = ls.loop_id\n  inner join subfield_sensors sb on ls.subfield_id = sb.subfield_id\n  inner join sector_sensors ss on sb.sector_id = ss.sector_id\nWHERE\n  test_id = $test_id and ss.name = 'SSE'\n ) s1"
    }
   ]
  }
 ]
}