{
 "title": "ullage",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Date",
    "query": "select to_char(timestamp, 'YYYY/MM/DD') from ullage_operation order by 1"
   },
   {
    "name": "next_day",
    "query": "select to_char((${Date:singlequote}::timestamp + '1 Day'::interval), 'YYYY/MM/DD')\n"
   },
   {
    "name": "previous_day",
    "query": "select to_char((${Date:singlequote}::timestamp - '1 Day'::interval), 'YYYY/MM/DD')\n"
   },
   { "name": "Duration", "query": "'18 HOUR'" }
  ]
 },
 "panels": [
  {
   "title": "ullage_operation_time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    o.timestamp,\r\n    o.r1qja10aa001,\r\n    o.r1qja12aa001,\r\n    r.value AS r1qja80cl001\r\nFROM\r\n    (\r\n        SELECT\r\n            \"timestamp\",\r\n            r1qja10aa001,\r\n            r1qja12aa001\r\n        FROM\r\n            ullage_operation\r\n    ) AS o\r\nLEFT JOIN\r\n    (\r\n        SELECT\r\n            \"timestamp\",\r\n            value\r\n        FROM\r\n            ullage_raw_measurement\r\n        WHERE\r\n            sensor_id = 16\r\n    ) AS r\r\nON o.timestamp = r.\"timestamp\"\r\nWHERE\r\n    o.timestamp between ${Date:singlequote}::timestamp and ${Date:singlequote}::timestamp + ${Duration::raw}\r\nORDER BY\r\n    o.\"timestamp\";"
    },
    {
     "rawSql": "SELECT\r\n    t1.\"timestamp\",\r\n    t1.value AS \"r1qja78cp001\",\r\n    t2.value AS \"r1je_20cp901\"\r\nFROM\r\n    (\r\n        SELECT \"timestamp\",  value\r\n        FROM ullage_raw_measurement\r\n        WHERE sensor_id = 7\r\n       \r\n    ) AS t1\r\nLEFT JOIN\r\n    (\r\n        SELECT \"timestamp\",  value\r\n        FROM ullage_raw_measurement\r\n        WHERE sensor_id = 19\r\n       \r\n    ) AS t2\r\nON t1.\"timestamp\" = t2.\"timestamp\"\r\n-- where SUBSTRING(t1.timestamp::text, 1, 10) IN ( $Date )\r\nwhere \r\n    t1.timestamp between ${Date:singlequote}::timestamp and ${Date:singlequote}::timestamp + ${Duration::raw}\r\n\r\nORDER BY t1.\"timestamp\";"
    }
   ]
  },
  {
   "title": "A bar trend with the last 30 days of ullage_operation ON ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH on_off_times AS (\r\n    SELECT\r\n        timestamp,\r\n        operation,\r\n        LAG(timestamp) OVER (ORDER BY timestamp) AS prev_timestamp,\r\n        LAG(operation) OVER (ORDER BY timestamp) AS prev_operation,\r\n        DATE_TRUNC('day', timestamp) AS day_timestamp -- Truncate timestamp to day level\r\n    FROM ullage_operation\r\n    WHERE operation IN ('ON', 'OFF') -- Assuming 'ON' and 'OFF' are valid operation values\r\n\r\n)\r\nSELECT\r\n     TO_CHAR(day_timestamp::date, 'DD-MM-YYYY') AS day, -- Format date as '01-02-2024'\r\n\tsum(case when TO_CHAR(timestamp::date, 'DD-MM-YYYY') =TO_CHAR(prev_timestamp::date, 'DD-MM-YYYY') then (EXTRACT(EPOCH FROM (timestamp - prev_timestamp)))/3600\r\n\telse 0\r\n\tend) as duration\r\nFROM on_off_times\r\nWHERE operation = 'ON'  \r\n      AND timestamp >= '$Date'::date - INTERVAL '30 days' -- Last 30 days filter\r\n      AND timestamp <= '$Date'::date + INTERVAL '1 days'-- Reference date filter\r\nGROUP BY day_timestamp::date\r\nORDER BY day_timestamp::date;"
    }
   ]
  },
  {
   "title": "Temperature follow up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, r1qja10aa001,r1qja12aa001,r1qja78cp001,\r\n case when operation = 'ON' then 1 else 0 end as Oper\r\nFROM ullage_operation\r\nwhere \r\n    timestamp between ${Date:singlequote}::timestamp and ${Date:singlequote}::timestamp + ${Duration::raw}\r\nORDER BY timestamp;"
    },
    {
     "rawSql": "SELECT \"timestamp\",\r\n       MAX(CASE WHEN sensor_id = 1 THEN value END) AS R1QJA78CT001,\r\n       MAX(CASE WHEN sensor_id = 2 THEN value END) AS R1QJA78CT002,\r\n       MAX(CASE WHEN sensor_id = 5 THEN value END) AS R1QJA80CT001,\r\n       MAX(CASE WHEN sensor_id = 6 THEN value END) AS R1QJA82CT001\r\nFROM ullage_raw_measurement\r\nWHERE sensor_id IN (1, 2, 5, 6) AND  \r\n       timestamp between ${Date:singlequote}::timestamp and ${Date:singlequote}::timestamp + ${Duration::raw}\r\nGROUP BY \"timestamp\"\r\nORDER BY \"timestamp\";"
    }
   ]
  },
  {
   "title": "VOC values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, r1qja10aa001,r1qja12aa001,r1qja78cp001,\r\n case when operation = 'ON' then 1 else 0 end as Oper\r\n \r\nFROM ullage_operation\r\nwhere \r\n    timestamp between ${Date:singlequote}::timestamp and ${Date:singlequote}::timestamp + ${Duration::raw}\r\nORDER BY timestamp;\r\n\r\n\r\n"
    },
    {
     "rawSql": "\r\nSELECT \"timestamp\", value as R1QJA78CQ001 \r\nFROM \r\n    ullage_raw_measurement \r\nWHERE \r\n      sensor_id =17 AND \r\n      timestamp between ${Date:singlequote}::timestamp and ${Date:singlequote}::timestamp + ${Duration::raw}\r\norder by \r\n    timestamp"
    }
   ]
  },
  {
   "title": "HTF Recovered mass",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "WITH TemperatureData AS (\r\n    SELECT timestamp, value AS temperature_value\r\n    FROM ullage_raw_measurement\r\n    WHERE sensor_id = 5 -- R1QJA80CT001\r\n),\r\nFlowData AS (\r\n    SELECT timestamp, value AS flow_value\r\n    FROM ullage_raw_measurement\r\n    WHERE sensor_id = 18 -- R1JE_40CF001\r\n),\r\nCalculations AS (\r\n    SELECT\r\n        t.timestamp,\r\n        f.flow_value AS \"R1JE_40CF001\",\r\n        t.temperature_value AS \"R1QJA80CT001\",\r\n        1065.05375654492 - 0.595426707667444 * t.temperature_value - 0.000893338489101383 * (t.temperature_value * t.temperature_value) AS htf_density,\r\n        f.flow_value * (1065.05375654492 - 0.595426707667444 * t.temperature_value - 0.000893338489101383 * (t.temperature_value * t.temperature_value)) * 10/3600 AS \"Recovered_mass_ton\"\r\n    FROM\r\n        FlowData f\r\n    JOIN\r\n        TemperatureData t ON t.timestamp = f.timestamp\r\n)\r\nSELECT\r\n    -- timestamp::date AS date_1,\r\n    TO_CHAR(timestamp::date, 'YYYY-MM-DD') AS date_1,\r\n    SUM(\"Recovered_mass_ton\") AS cumulative_recovered_mass_ton\r\nFROM\r\n    Calculations\r\nWHERE\r\n    timestamp >= '$Date'::date - INTERVAL '60 days' -- Last 60 days filter\r\n    AND timestamp <= '$Date'::date + INTERVAL '1 days'-- Reference date filter\r\nGROUP BY\r\n    timestamp::date\r\nORDER BY\r\n    timestamp::date;"
    }
   ]
  },
  {
   "title": "Total alarms per day",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH formatted_dates AS (\r\n    SELECT\r\n        DATE(alarm_start) AS alarm_date,\r\n        COUNT(*) AS total_alarms,\r\n        SUM(CASE WHEN uad.name IN ('HH', 'LL') THEN 1 ELSE 0 END) AS critical_alarms\r\n    FROM\r\n        ullage_alarm_record uar\r\n    JOIN\r\n        ullage_alarm_definition uad ON uar.alarm_definition_id = uad.id\r\n    GROUP BY\r\n        DATE(alarm_start)\r\n)\r\nSELECT\r\n    TO_CHAR(alarm_date, 'YYYY/MM/DD') AS alarm_date,\r\n    total_alarms\r\nFROM\r\n    formatted_dates\r\nWHERE\r\n    alarm_date = ${Date:singlequote}::timestamp \r\nORDER BY\r\n    alarm_date;\r\n"
    }
   ]
  },
  {
   "title": "Critical alarms(HH and LL alarms)per day",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH formatted_dates AS (\r\n    SELECT\r\n        DATE(alarm_start) AS alarm_date,\r\n        COUNT(*) AS total_alarms,\r\n        SUM(CASE WHEN uad.name IN ('HH', 'LL') THEN 1 ELSE 0 END) AS critical_alarms\r\n    FROM\r\n        ullage_alarm_record uar\r\n    JOIN\r\n        ullage_alarm_definition uad ON uar.alarm_definition_id = uad.id\r\n    -- WHERE\r\n    --     alarm_start >= $__timeFrom() AND alarm_start <= $__timeTo()  -- Apply time range filter\r\n    GROUP BY\r\n        DATE(alarm_start)\r\n)\r\nSELECT\r\n    TO_CHAR(alarm_date, 'DD-MM-YYYY') AS alarm_date,\r\n    critical_alarms\r\nFROM\r\n    formatted_dates\r\nWHERE \r\n    alarm_date = ${Date:singlequote}::timestamp \r\nORDER BY\r\n    alarm_date;\r\n"
    }
   ]
  },
  {
   "title": "Alarm process",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT us.kks,\r\n       uar.alarm_start,\r\n       uar.duration,\r\n       uar.value as value_Avg,\r\n       uar.value_max_min,\r\n       uad.name || '> ' || uad.value || ' ' || uad.unit AS alarm\r\nFROM public.ullage_sensor us\r\nJOIN public.ullage_alarm_definition uad ON us.id = uad.sensor_id\r\nJOIN public.ullage_alarm_record uar ON uad.id = uar.alarm_definition_id\r\nwhere \r\n      uar.alarm_start between ${Date:singlequote}::timestamp and  ${Date:singlequote}::timestamp + ${Duration::raw};"
    }
   ]
  },
  {
   "title": "Alarm process duplicate",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "       SELECT ds.kks,\r\n       uar.alarm_start,\r\n       uar.duration,\r\n       uar.value as value_Avg,\r\n       uar.value_max_min,\r\n       CASE\r\n           WHEN uad.name IN ('H', 'HH', 'HHH') THEN uad.name || '> ' || uad.value || ' ' || uad.unit\r\n           ELSE uad.name || '< ' || uad.value || ' ' || uad.unit\r\n      end as alarm\r\nFROM public.ullage_sensor ds\r\nJOIN public.ullage_alarm_definition uad ON ds.id = uad.sensor_id\r\nJOIN public.ullage_alarm_record uar ON uad.id = uar.alarm_definition_id\r\nwhere \r\n      uar.alarm_start between ${Date:singlequote}::timestamp and  ${Date:singlequote}::timestamp + ${Duration::raw};\r\n\r\n"
    }
   ]
  }
 ]
}